### ISSUE TITLE
ctrl+f search results appear behind search bar

### ISSUE THREAD

**Issue by supersaiyansubtlety** [QuiltMC/enigma#181] opened 2024-01-18 02:35 UTC
If a ctrl-f search result is too low on the page to be seen without scrolling, the search function scrolls to it, but doesn't account for the height of the search bar. To actually see the result you need to manually scroll farther or cancel the search so the search bar isn't in the way.
![after searching](https://github.com/QuiltMC/enigma/assets/618276/56785f52-4752-46a7-a650-c4cd11927c3e)
![after scrolling](https://github.com/QuiltMC/enigma/assets/618276/09cc1f9d-3ba5-4bde-96d8-24b19b42717a)

**Comment by ix0rai** [comment] 2024-01-26 04:19
duplicate of https://github.com/QuiltMC/syntaxpain/issues/1, I'll leave both open until I find the fix

**Comment by ix0rai** [comment] 2024-03-03 18:00
fixed by iota with https://github.com/QuiltMC/syntaxpain/pull/3 !

**Closed by ix0rai** 2024-03-03 18:00 UTC
Labels: bug, user interface
